services:
  db:
    image: mongo:7
    container_name: db_giardino_digitale
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - 'db_data:/data/db'
  minio:
    image: 'quay.io/minio/minio:latest'
    container_name: minio_giardino_digitale
    command: 'server /data --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_ACCESS_KEY}
    volumes:
      - 'minio_data:/data'

volumes:
  db_data:
    driver: local
  minio_data:
    driver: local
