services:
  app:
    container_name: join-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URI: ${DATABASE_URI}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}

        # Minio (S3 Storage)
        S3_ENDPOINT: ${S3_ENDPOINT}
        S3_BUCKET: ${S3_BUCKET}
        S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
        S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
        S3_REGION: ${S3_REGION}

        # MongoDB (Database)
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

        # SMTP
        SMTP_HOST: ${SMTP_HOST}
        SMTP_PORT: ${SMTP_PORT}
        SMTP_FROM_ADDRESS: ${SMTP_FROM_ADDRESS}
        SMTP_FROM_NAME: ${SMTP_FROM_NAME}
        SMTP_AUTH_USER: ${SMTP_AUTH_USER}
        SMTP_AUTH_PASSWORD: ${SMTP_AUTH_PASSWORD}

        # Stripe
        STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
        STRIPE_WEBHOOKS_ENDPOINT_SECRET: ${STRIPE_WEBHOOKS_ENDPOINT_SECRET}

        # Posthog
        NEXT_PUBLIC_POSTHOG_KEY: ${NEXT_PUBLIC_POSTHOG_KEY}
        NEXT_PUBLIC_POSTHOG_HOST: ${NEXT_PUBLIC_POSTHOG_HOST}
    environment:
      DATABASE_URI: ${DATABASE_URI}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}

      # Minio (S3 Storage)
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_REGION: ${S3_REGION}

      # MongoDB (Database)
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

      # SMTP
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_FROM_ADDRESS: ${SMTP_FROM_ADDRESS}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      SMTP_AUTH_USER: ${SMTP_AUTH_USER}
      SMTP_AUTH_PASSWORD: ${SMTP_AUTH_PASSWORD}

      # Stripe
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      STRIPE_WEBHOOKS_ENDPOINT_SECRET: ${STRIPE_WEBHOOKS_ENDPOINT_SECRET}

      # Posthog
      NEXT_PUBLIC_POSTHOG_KEY: ${NEXT_PUBLIC_POSTHOG_KEY}
      NEXT_PUBLIC_POSTHOG_HOST: ${NEXT_PUBLIC_POSTHOG_HOST}

      # Authentik
      AUTHENTIK_SERVER_URL: ${AUTHENTIK_SERVER_URL}
      AUTHENTIK_CLIENT_ID: ${AUTHENTIK_CLIENT_ID}
      AUTHENTIK_CLIENT_SECRET: ${AUTHENTIK_CLIENT_SECRET}
    ports:
      - '3000:3000'
