services:
  credimi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PAYLOAD_SECRET=${PAYLOAD_SECRET:-payloadsecret}
      - DATABASE_URI=${DATABASE_URI:-file:/app/data/orto-digitale.db}
      - MEDIA_DIR=${MEDIA_DIR:-/app/data/files/media}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL:-https://orto-digitale.lascuolaopensource.org}
    ports:
      - 3000:3000
    volumes:
      - ./data/:/app/data
